server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    queue-url:
      user-data-request: ${AWS_SQS_QUEUE_URL_USER_DATA_REQUEST}
      user-data-response: ${AWS_SQS_QUEUE_URL_USER_DATA_RESPONSE}
    dlq-url:
      user-data-request: ${AWS_SQS_DLQ_URL_USER_DATA_REQUEST}
      user-data-response: ${AWS_SQS_DLQ_URL_USER_DATA_RESPONSE}

    fixed-rate-ms: ${AWS_SQS_FIXED_RATE_MS:60000} # 1 minuto (em milissegundos)
    max-messages: ${AWS_SQS_MAX_MESSAGES:5}       # Máximo de mensagens por requisição
    wait-time-seconds: ${AWS_SQS_WAIT_TIME_SECONDS:10} # Tempo de espera do long polling
  sns:
    userCreatedTopic: ${AWS_SNS_TOPIC_ARN_USER_CREATED}

spring:
  application:
    name: picbank-user-service

  datasource:
    url: jdbc:postgresql://${POSTGRE_RDS_ENDPOINT}:5432/picbank-user-db
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Can be changed to "validate" or "none" in production
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  messages:
    basename: messages
    encoding: ${SPRING_MESSAGES_ENCODING:UTF-8}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
